name: "Setup"
description: "Setup monorepo packages"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build packages
      run: |
        pnpm turbo build:package
      shell: bash

    - name: Add env for jobs-dashboard
      run: |
        cd apps/jobs-dashboard
        echo "VITE_API_URL=http://localhost:3001" > .env.local
      shell: bash
