name: Run Database Migrations

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Check persistent infra has been deployed
      working-directory: infra/persistent
      run: |
        terraform plan -detailed-exitcode || exit_code=$?
        if [ "$exit_code" -eq 2 ]; then
          echo "❌ Drift detected or resources not fully deployed"
          exit 1
        elif [ "$exit_code" -eq 1 ]; then
          echo "❌ Terraform error"
          exit 1
        fi
