name: Setup
on:
  pull_request:
    paths:
      - "app/**"
      - "api/**"
      - "shared/**"

runs:
  using: composite

  steps:
    - name: Install pnpm
      shell: bash
      uses: pnpm/action-setup@v4

    - name: Set up Node.js
      shell: bash
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install
