// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RolesId } from './Roles';

/** Identifier type for hire_me.applications */
export type ApplicationsId = string & { __brand: 'ApplicationsId' };

/** Represents the table hire_me.applications */
export default interface Applications {
  id: ApplicationsId;

  role_id: RolesId;

  code_hash: string;

  cover_letter: string;
}

/** Represents the initializer for the table hire_me.applications */
export interface ApplicationsInitializer {
  id: ApplicationsId;

  role_id: RolesId;

  code_hash: string;

  cover_letter: string;
}

/** Represents the mutator for the table hire_me.applications */
export interface ApplicationsMutator {
  id?: ApplicationsId;

  role_id?: RolesId;

  code_hash?: string;

  cover_letter?: string;
}
