// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for hire_me.company */
export type CompanyId = number & { __brand: 'CompanyId' };

/** Represents the table hire_me.company */
export default interface Company {
  id: CompanyId;

  name: string;
}

/** Represents the initializer for the table hire_me.company */
export interface CompanyInitializer {
  name: string;
}

/** Represents the mutator for the table hire_me.company */
export interface CompanyMutator {
  name?: string;
}
