// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for hire_me.companies */
export type CompaniesId = number & { __brand: 'CompaniesId' };

/** Represents the table hire_me.companies */
export default interface Companies {
  id: CompaniesId;

  name: string;
}

/** Represents the initializer for the table hire_me.companies */
export interface CompaniesInitializer {
  name: string;
}

/** Represents the mutator for the table hire_me.companies */
export interface CompaniesMutator {
  name?: string;
}
