// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RolesId } from './Roles';
import type { default as RequirementMatchLevel } from './RequirementMatchLevel';

/** Identifier type for hire_me.requirements */
export type RequirementsId = string & { __brand: 'RequirementsId' };

/** Represents the table hire_me.requirements */
export default interface Requirements {
  id: RequirementsId;

  role_id: RolesId;

  requirement: string;

  match_level: RequirementMatchLevel;

  match_justification: string;

  bonus: boolean;
}

/** Represents the initializer for the table hire_me.requirements */
export interface RequirementsInitializer {
  id: RequirementsId;

  role_id: RolesId;

  requirement: string;

  match_level: RequirementMatchLevel;

  match_justification: string;

  bonus: boolean;
}

/** Represents the mutator for the table hire_me.requirements */
export interface RequirementsMutator {
  id?: RequirementsId;

  role_id?: RolesId;

  requirement?: string;

  match_level?: RequirementMatchLevel;

  match_justification?: string;

  bonus?: boolean;
}
