// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RoleId } from './Role';
import type { default as RequirementMatchLevel } from './RequirementMatchLevel';

/** Identifier type for hire_me.requirement */
export type RequirementId = number & { __brand: 'RequirementId' };

/** Represents the table hire_me.requirement */
export default interface Requirement {
  id: RequirementId;

  role_id: RoleId;

  requirement: string;

  match_level: RequirementMatchLevel;

  match_justification: string;

  bonus: boolean;
}

/** Represents the initializer for the table hire_me.requirement */
export interface RequirementInitializer {
  role_id: RoleId;

  requirement: string;

  match_level: RequirementMatchLevel;

  match_justification: string;

  bonus: boolean;
}

/** Represents the mutator for the table hire_me.requirement */
export interface RequirementMutator {
  role_id?: RoleId;

  requirement?: string;

  match_level?: RequirementMatchLevel;

  match_justification?: string;

  bonus?: boolean;
}
