// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum hire_me.requirement_match_level */
type RequirementMatchLevel = 
  | 'exceeded'
  | 'met'
  | 'somewhat_met'
  | 'room_for_growth';

export default RequirementMatchLevel;
