// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CompaniesId } from './Companies';

/** Identifier type for hire_me.roles */
export type RolesId = number & { __brand: 'RolesId' };

/** Represents the table hire_me.roles */
export default interface Roles {
  id: RolesId;

  company_id: CompaniesId;

  title: string;
}

/** Represents the initializer for the table hire_me.roles */
export interface RolesInitializer {
  company_id: CompaniesId;

  title: string;
}

/** Represents the mutator for the table hire_me.roles */
export interface RolesMutator {
  company_id?: CompaniesId;

  title?: string;
}
