// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CompanyId } from './Company';

/** Identifier type for hire_me.role */
export type RoleId = number & { __brand: 'RoleId' };

/** Represents the table hire_me.role */
export default interface Role {
  id: RoleId;

  company_id: CompanyId;

  title: string;
}

/** Represents the initializer for the table hire_me.role */
export interface RoleInitializer {
  company_id: CompanyId;

  title: string;
}

/** Represents the mutator for the table hire_me.role */
export interface RoleMutator {
  company_id?: CompanyId;

  title?: string;
}
