/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardRolesImport } from './routes/dashboard/roles'
import { Route as DashboardAddRoleRouteImport } from './routes/dashboard/add-role/route'
import { Route as DashboardRoleRoleIdImport } from './routes/dashboard/role.$roleId'
import { Route as DashboardAddRoleRoleImport } from './routes/dashboard/add-role/role'
import { Route as DashboardAddRoleLocationImport } from './routes/dashboard/add-role/location'
import { Route as DashboardAddRoleContractImport } from './routes/dashboard/add-role/contract'
import { Route as DashboardAddRoleCompanyImport } from './routes/dashboard/add-role/company'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardRolesRoute = DashboardRolesImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAddRoleRouteRoute = DashboardAddRoleRouteImport.update({
  id: '/add-role',
  path: '/add-role',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardRoleRoleIdRoute = DashboardRoleRoleIdImport.update({
  id: '/role/$roleId',
  path: '/role/$roleId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAddRoleRoleRoute = DashboardAddRoleRoleImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => DashboardAddRoleRouteRoute,
} as any)

const DashboardAddRoleLocationRoute = DashboardAddRoleLocationImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => DashboardAddRoleRouteRoute,
} as any)

const DashboardAddRoleContractRoute = DashboardAddRoleContractImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => DashboardAddRoleRouteRoute,
} as any)

const DashboardAddRoleCompanyRoute = DashboardAddRoleCompanyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => DashboardAddRoleRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/add-role': {
      id: '/dashboard/add-role'
      path: '/add-role'
      fullPath: '/dashboard/add-role'
      preLoaderRoute: typeof DashboardAddRoleRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/add-role/company': {
      id: '/dashboard/add-role/company'
      path: '/company'
      fullPath: '/dashboard/add-role/company'
      preLoaderRoute: typeof DashboardAddRoleCompanyImport
      parentRoute: typeof DashboardAddRoleRouteImport
    }
    '/dashboard/add-role/contract': {
      id: '/dashboard/add-role/contract'
      path: '/contract'
      fullPath: '/dashboard/add-role/contract'
      preLoaderRoute: typeof DashboardAddRoleContractImport
      parentRoute: typeof DashboardAddRoleRouteImport
    }
    '/dashboard/add-role/location': {
      id: '/dashboard/add-role/location'
      path: '/location'
      fullPath: '/dashboard/add-role/location'
      preLoaderRoute: typeof DashboardAddRoleLocationImport
      parentRoute: typeof DashboardAddRoleRouteImport
    }
    '/dashboard/add-role/role': {
      id: '/dashboard/add-role/role'
      path: '/role'
      fullPath: '/dashboard/add-role/role'
      preLoaderRoute: typeof DashboardAddRoleRoleImport
      parentRoute: typeof DashboardAddRoleRouteImport
    }
    '/dashboard/role/$roleId': {
      id: '/dashboard/role/$roleId'
      path: '/role/$roleId'
      fullPath: '/dashboard/role/$roleId'
      preLoaderRoute: typeof DashboardRoleRoleIdImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardAddRoleRouteRouteChildren {
  DashboardAddRoleCompanyRoute: typeof DashboardAddRoleCompanyRoute
  DashboardAddRoleContractRoute: typeof DashboardAddRoleContractRoute
  DashboardAddRoleLocationRoute: typeof DashboardAddRoleLocationRoute
  DashboardAddRoleRoleRoute: typeof DashboardAddRoleRoleRoute
}

const DashboardAddRoleRouteRouteChildren: DashboardAddRoleRouteRouteChildren = {
  DashboardAddRoleCompanyRoute: DashboardAddRoleCompanyRoute,
  DashboardAddRoleContractRoute: DashboardAddRoleContractRoute,
  DashboardAddRoleLocationRoute: DashboardAddRoleLocationRoute,
  DashboardAddRoleRoleRoute: DashboardAddRoleRoleRoute,
}

const DashboardAddRoleRouteRouteWithChildren =
  DashboardAddRoleRouteRoute._addFileChildren(
    DashboardAddRoleRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAddRoleRouteRoute: typeof DashboardAddRoleRouteRouteWithChildren
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRoleRoleIdRoute: typeof DashboardRoleRoleIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAddRoleRouteRoute: DashboardAddRoleRouteRouteWithChildren,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRoleRoleIdRoute: DashboardRoleRoleIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/add-role': typeof DashboardAddRoleRouteRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/add-role/company': typeof DashboardAddRoleCompanyRoute
  '/dashboard/add-role/contract': typeof DashboardAddRoleContractRoute
  '/dashboard/add-role/location': typeof DashboardAddRoleLocationRoute
  '/dashboard/add-role/role': typeof DashboardAddRoleRoleRoute
  '/dashboard/role/$roleId': typeof DashboardRoleRoleIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/add-role': typeof DashboardAddRoleRouteRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/add-role/company': typeof DashboardAddRoleCompanyRoute
  '/dashboard/add-role/contract': typeof DashboardAddRoleContractRoute
  '/dashboard/add-role/location': typeof DashboardAddRoleLocationRoute
  '/dashboard/add-role/role': typeof DashboardAddRoleRoleRoute
  '/dashboard/role/$roleId': typeof DashboardRoleRoleIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/add-role': typeof DashboardAddRoleRouteRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/add-role/company': typeof DashboardAddRoleCompanyRoute
  '/dashboard/add-role/contract': typeof DashboardAddRoleContractRoute
  '/dashboard/add-role/location': typeof DashboardAddRoleLocationRoute
  '/dashboard/add-role/role': typeof DashboardAddRoleRoleRoute
  '/dashboard/role/$roleId': typeof DashboardRoleRoleIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/add-role'
    | '/dashboard/roles'
    | '/dashboard/'
    | '/dashboard/add-role/company'
    | '/dashboard/add-role/contract'
    | '/dashboard/add-role/location'
    | '/dashboard/add-role/role'
    | '/dashboard/role/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/add-role'
    | '/dashboard/roles'
    | '/dashboard'
    | '/dashboard/add-role/company'
    | '/dashboard/add-role/contract'
    | '/dashboard/add-role/location'
    | '/dashboard/add-role/role'
    | '/dashboard/role/$roleId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/add-role'
    | '/dashboard/roles'
    | '/dashboard/'
    | '/dashboard/add-role/company'
    | '/dashboard/add-role/contract'
    | '/dashboard/add-role/location'
    | '/dashboard/add-role/role'
    | '/dashboard/role/$roleId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/add-role",
        "/dashboard/roles",
        "/dashboard/",
        "/dashboard/role/$roleId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/dashboard/add-role": {
      "filePath": "dashboard/add-role/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/add-role/company",
        "/dashboard/add-role/contract",
        "/dashboard/add-role/location",
        "/dashboard/add-role/role"
      ]
    },
    "/dashboard/roles": {
      "filePath": "dashboard/roles.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/add-role/company": {
      "filePath": "dashboard/add-role/company.tsx",
      "parent": "/dashboard/add-role"
    },
    "/dashboard/add-role/contract": {
      "filePath": "dashboard/add-role/contract.tsx",
      "parent": "/dashboard/add-role"
    },
    "/dashboard/add-role/location": {
      "filePath": "dashboard/add-role/location.tsx",
      "parent": "/dashboard/add-role"
    },
    "/dashboard/add-role/role": {
      "filePath": "dashboard/add-role/role.tsx",
      "parent": "/dashboard/add-role"
    },
    "/dashboard/role/$roleId": {
      "filePath": "dashboard/role.$roleId.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
