/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as authedRouteImport } from './routes/(authed)/route'
import { Route as IndexImport } from './routes/index'
import { Route as authedRolesImport } from './routes/(authed)/roles'
import { Route as authedAddRoleRouteImport } from './routes/(authed)/add-role/route'
import { Route as authedAddRoleRoleImport } from './routes/(authed)/add-role/role'
import { Route as authedAddRoleCompanyImport } from './routes/(authed)/add-role/company'
import { Route as authedRoleRoleIdIndexImport } from './routes/(authed)/role.$roleId.index'
import { Route as authedRoleRoleIdSalaryAddImport } from './routes/(authed)/role.$roleId.salary.add'
import { Route as authedRoleRoleIdRequirementsAddImport } from './routes/(authed)/role.$roleId.requirements.add'
import { Route as authedRoleRoleIdLocationAddImport } from './routes/(authed)/role.$roleId.location.add'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const authedRouteRoute = authedRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authedRolesRoute = authedRolesImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => authedRouteRoute,
} as any)

const authedAddRoleRouteRoute = authedAddRoleRouteImport.update({
  id: '/add-role',
  path: '/add-role',
  getParentRoute: () => authedRouteRoute,
} as any)

const authedAddRoleRoleRoute = authedAddRoleRoleImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => authedAddRoleRouteRoute,
} as any)

const authedAddRoleCompanyRoute = authedAddRoleCompanyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => authedAddRoleRouteRoute,
} as any)

const authedRoleRoleIdIndexRoute = authedRoleRoleIdIndexImport.update({
  id: '/role/$roleId/',
  path: '/role/$roleId/',
  getParentRoute: () => authedRouteRoute,
} as any)

const authedRoleRoleIdSalaryAddRoute = authedRoleRoleIdSalaryAddImport.update({
  id: '/role/$roleId/salary/add',
  path: '/role/$roleId/salary/add',
  getParentRoute: () => authedRouteRoute,
} as any)

const authedRoleRoleIdRequirementsAddRoute =
  authedRoleRoleIdRequirementsAddImport.update({
    id: '/role/$roleId/requirements/add',
    path: '/role/$roleId/requirements/add',
    getParentRoute: () => authedRouteRoute,
  } as any)

const authedRoleRoleIdLocationAddRoute =
  authedRoleRoleIdLocationAddImport.update({
    id: '/role/$roleId/location/add',
    path: '/role/$roleId/location/add',
    getParentRoute: () => authedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(authed)': {
      id: '/(authed)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authedRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/(authed)/add-role': {
      id: '/(authed)/add-role'
      path: '/add-role'
      fullPath: '/add-role'
      preLoaderRoute: typeof authedAddRoleRouteImport
      parentRoute: typeof authedRouteImport
    }
    '/(authed)/roles': {
      id: '/(authed)/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof authedRolesImport
      parentRoute: typeof authedRouteImport
    }
    '/(authed)/add-role/company': {
      id: '/(authed)/add-role/company'
      path: '/company'
      fullPath: '/add-role/company'
      preLoaderRoute: typeof authedAddRoleCompanyImport
      parentRoute: typeof authedAddRoleRouteImport
    }
    '/(authed)/add-role/role': {
      id: '/(authed)/add-role/role'
      path: '/role'
      fullPath: '/add-role/role'
      preLoaderRoute: typeof authedAddRoleRoleImport
      parentRoute: typeof authedAddRoleRouteImport
    }
    '/(authed)/role/$roleId/': {
      id: '/(authed)/role/$roleId/'
      path: '/role/$roleId'
      fullPath: '/role/$roleId'
      preLoaderRoute: typeof authedRoleRoleIdIndexImport
      parentRoute: typeof authedRouteImport
    }
    '/(authed)/role/$roleId/location/add': {
      id: '/(authed)/role/$roleId/location/add'
      path: '/role/$roleId/location/add'
      fullPath: '/role/$roleId/location/add'
      preLoaderRoute: typeof authedRoleRoleIdLocationAddImport
      parentRoute: typeof authedRouteImport
    }
    '/(authed)/role/$roleId/requirements/add': {
      id: '/(authed)/role/$roleId/requirements/add'
      path: '/role/$roleId/requirements/add'
      fullPath: '/role/$roleId/requirements/add'
      preLoaderRoute: typeof authedRoleRoleIdRequirementsAddImport
      parentRoute: typeof authedRouteImport
    }
    '/(authed)/role/$roleId/salary/add': {
      id: '/(authed)/role/$roleId/salary/add'
      path: '/role/$roleId/salary/add'
      fullPath: '/role/$roleId/salary/add'
      preLoaderRoute: typeof authedRoleRoleIdSalaryAddImport
      parentRoute: typeof authedRouteImport
    }
  }
}

// Create and export the route tree

interface authedAddRoleRouteRouteChildren {
  authedAddRoleCompanyRoute: typeof authedAddRoleCompanyRoute
  authedAddRoleRoleRoute: typeof authedAddRoleRoleRoute
}

const authedAddRoleRouteRouteChildren: authedAddRoleRouteRouteChildren = {
  authedAddRoleCompanyRoute: authedAddRoleCompanyRoute,
  authedAddRoleRoleRoute: authedAddRoleRoleRoute,
}

const authedAddRoleRouteRouteWithChildren =
  authedAddRoleRouteRoute._addFileChildren(authedAddRoleRouteRouteChildren)

interface authedRouteRouteChildren {
  authedAddRoleRouteRoute: typeof authedAddRoleRouteRouteWithChildren
  authedRolesRoute: typeof authedRolesRoute
  authedRoleRoleIdIndexRoute: typeof authedRoleRoleIdIndexRoute
  authedRoleRoleIdLocationAddRoute: typeof authedRoleRoleIdLocationAddRoute
  authedRoleRoleIdRequirementsAddRoute: typeof authedRoleRoleIdRequirementsAddRoute
  authedRoleRoleIdSalaryAddRoute: typeof authedRoleRoleIdSalaryAddRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedAddRoleRouteRoute: authedAddRoleRouteRouteWithChildren,
  authedRolesRoute: authedRolesRoute,
  authedRoleRoleIdIndexRoute: authedRoleRoleIdIndexRoute,
  authedRoleRoleIdLocationAddRoute: authedRoleRoleIdLocationAddRoute,
  authedRoleRoleIdRequirementsAddRoute: authedRoleRoleIdRequirementsAddRoute,
  authedRoleRoleIdSalaryAddRoute: authedRoleRoleIdSalaryAddRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/add-role': typeof authedAddRoleRouteRouteWithChildren
  '/roles': typeof authedRolesRoute
  '/add-role/company': typeof authedAddRoleCompanyRoute
  '/add-role/role': typeof authedAddRoleRoleRoute
  '/role/$roleId': typeof authedRoleRoleIdIndexRoute
  '/role/$roleId/location/add': typeof authedRoleRoleIdLocationAddRoute
  '/role/$roleId/requirements/add': typeof authedRoleRoleIdRequirementsAddRoute
  '/role/$roleId/salary/add': typeof authedRoleRoleIdSalaryAddRoute
}

export interface FileRoutesByTo {
  '/': typeof authedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/add-role': typeof authedAddRoleRouteRouteWithChildren
  '/roles': typeof authedRolesRoute
  '/add-role/company': typeof authedAddRoleCompanyRoute
  '/add-role/role': typeof authedAddRoleRoleRoute
  '/role/$roleId': typeof authedRoleRoleIdIndexRoute
  '/role/$roleId/location/add': typeof authedRoleRoleIdLocationAddRoute
  '/role/$roleId/requirements/add': typeof authedRoleRoleIdRequirementsAddRoute
  '/role/$roleId/salary/add': typeof authedRoleRoleIdSalaryAddRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(authed)': typeof authedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(authed)/add-role': typeof authedAddRoleRouteRouteWithChildren
  '/(authed)/roles': typeof authedRolesRoute
  '/(authed)/add-role/company': typeof authedAddRoleCompanyRoute
  '/(authed)/add-role/role': typeof authedAddRoleRoleRoute
  '/(authed)/role/$roleId/': typeof authedRoleRoleIdIndexRoute
  '/(authed)/role/$roleId/location/add': typeof authedRoleRoleIdLocationAddRoute
  '/(authed)/role/$roleId/requirements/add': typeof authedRoleRoleIdRequirementsAddRoute
  '/(authed)/role/$roleId/salary/add': typeof authedRoleRoleIdSalaryAddRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/add-role'
    | '/roles'
    | '/add-role/company'
    | '/add-role/role'
    | '/role/$roleId'
    | '/role/$roleId/location/add'
    | '/role/$roleId/requirements/add'
    | '/role/$roleId/salary/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/add-role'
    | '/roles'
    | '/add-role/company'
    | '/add-role/role'
    | '/role/$roleId'
    | '/role/$roleId/location/add'
    | '/role/$roleId/requirements/add'
    | '/role/$roleId/salary/add'
  id:
    | '__root__'
    | '/'
    | '/(authed)'
    | '/login'
    | '/(authed)/add-role'
    | '/(authed)/roles'
    | '/(authed)/add-role/company'
    | '/(authed)/add-role/role'
    | '/(authed)/role/$roleId/'
    | '/(authed)/role/$roleId/location/add'
    | '/(authed)/role/$roleId/requirements/add'
    | '/(authed)/role/$roleId/salary/add'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedRouteRoute: typeof authedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedRouteRoute: authedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(authed)",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(authed)": {
      "filePath": "(authed)/route.tsx",
      "children": [
        "/(authed)/add-role",
        "/(authed)/roles",
        "/(authed)/role/$roleId/",
        "/(authed)/role/$roleId/location/add",
        "/(authed)/role/$roleId/requirements/add",
        "/(authed)/role/$roleId/salary/add"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/(authed)/add-role": {
      "filePath": "(authed)/add-role/route.tsx",
      "parent": "/(authed)",
      "children": [
        "/(authed)/add-role/company",
        "/(authed)/add-role/role"
      ]
    },
    "/(authed)/roles": {
      "filePath": "(authed)/roles.tsx",
      "parent": "/(authed)"
    },
    "/(authed)/add-role/company": {
      "filePath": "(authed)/add-role/company.tsx",
      "parent": "/(authed)/add-role"
    },
    "/(authed)/add-role/role": {
      "filePath": "(authed)/add-role/role.tsx",
      "parent": "/(authed)/add-role"
    },
    "/(authed)/role/$roleId/": {
      "filePath": "(authed)/role.$roleId.index.tsx",
      "parent": "/(authed)"
    },
    "/(authed)/role/$roleId/location/add": {
      "filePath": "(authed)/role.$roleId.location.add.tsx",
      "parent": "/(authed)"
    },
    "/(authed)/role/$roleId/requirements/add": {
      "filePath": "(authed)/role.$roleId.requirements.add.tsx",
      "parent": "/(authed)"
    },
    "/(authed)/role/$roleId/salary/add": {
      "filePath": "(authed)/role.$roleId.salary.add.tsx",
      "parent": "/(authed)"
    }
  }
}
ROUTE_MANIFEST_END */
