name: Run App Tests

on:
  pull_request:
    paths:
      - "app/**"

jobs:
  app-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd app
          pnpm install

      - name: Run tests
        run: |
          cd app
          pnpm test
