name: Type Checking and Linting

on:
  pull_request:
    paths:
      - "app/**"
      - "api/**"
      - "shared/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [app, api, shared]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd ${{ matrix.package }}
          pnpm install

      - name: Check
        run: |
          cd ${{ matrix.package }}
          pnpm test
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [app, api, shared]
    needs: setup
    steps:
      - name: Type Check
        run: |
          cd ${{ matrix.package }}
          pnpm typecheck
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [app, api, shared]
    needs: setup
    steps:
      - name: Linting
        run: |
          cd ${{ matrix.package }}
          pnpm lint
