name: "💽 🧪 DB Verification"

on: ["pull_request"]

jobs:
  sqitch-deploy-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup

      - name: Install Sqitch
        run: |
          sudo apt-get update
          sudo apt-get install -y sqitch

      - name: Up db
        run: |
          cd apps/api
          pnpm db:ci:up

      - name: Deploy and verify db
        run: |
          cd apps/api
          pnpm db:ci:verify
