name: Run Database Migrations

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: db-deployment
  # push:
  #   branches: [main, db-deployment]
  #   paths:
  #     - "apps/api/db/sqitch.plan"
  #     - ".github/workflows/migrations.yml"

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: migration-runner

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f infra/images/Dockerfile.migrations .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Start CodeBuild Project
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sqitch-migrations
          region: ${{ env.AWS_REGION }}
          wait: true
          source-type-override: "NO_SOURCE"
