name: Run Database Migrations

on:
  push:
    branches: [main]
    paths:
      - "apps/api/db/sqitch.plan"
      - ".github/workflows/migrations.yml"

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-southeast-2

      - name: Start CodeBuild Project
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sqitch-migrations
          region: ap-southeast-2
