name: Do Not Merge WIP PRs

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  wip-label-check:
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: PR is WIP ❌
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'wip')
        run: |
          echo "Pull request is labeled as WIP"
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1

      - name: PR is mergeable ✅
        if: ${{ !contains(join(github.event.pull_request.labels.*.name, ','), 'wip') }}
        run: echo "No WIP label found. All good to merge!"
